changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - "**/*.test.{js,ts,jsx,tsx}"
  - "**/test.{js,ts,jsx,tsx}"
  - "**/*.spec.{js,ts,jsx,tsx}"

compressionLevel: 0

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableScripts: false

nmMode: hardlinks-local

nodeLinker: node-modules

npmMinimalAgeGate: 2880

npmPreapprovedPackages:
  - "@belgattitude/*"
  - "@flowblade/*"
  - "@httpx/*"
  - next
  - "@next/*"
  - "@azure/*"
  - prisma
  - "@prisma/*"
  - "@duckdb/*"
  - turbo
  - turbo-*
  - typebox
  - vite
  - "@vitejs/*"
  - vitest
  - "@vitest/*"
  - hono
  - "@sentry/*"
  - "@sentry-internal/*"
  - storybook
  - "@storybook/*"
  - esbuild
  - "@esbuild/*"
  - better-auth
  - better-call
  - "@better-auth/*"
  - "@typescript-eslint/*"
  - prettier
  - "@kubb/*"
  - "@redocly/*"
  - tsdown

npmPublishProvenance: true

npmRegistryServer: "https://registry.npmjs.org"

supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current

yarnPath: .yarn/releases/yarn-4.12.0.cjs
