compressionLevel: 0

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableScripts: false

nmMode: hardlinks-local

nodeLinker: node-modules

npmMinimalAgeGate: 2880
  
catalog:
  '@typescript/native-preview': 7.0.0-dev.20260415.1

npmPreapprovedPackages:
  - "@belgattitude/*"
  - "@flowblade/*"
  - "@httpx/*"
  - next
  - "@next/*"
  - "@azure/*"
  - prisma
  - "@prisma/*"
  - "@duckdb/*"
  - kysely
  - turbo
  - turbo-*
  - "@turbo/*"
  - typebox
  - vite
  - "@vitejs/*"
  - vitest
  - "@vitest/*"
  - hono
  - "@hono/*"
  - "@sentry/*"
  - "@sentry-internal/*"
  - storybook
  - "@storybook/*"
  - esbuild
  - "@esbuild/*"
  - better-auth
  - better-call
  - "@better-auth/*"
  - "@typescript-eslint/*"
  - prettier
  - "@kubb/*"
  - remeda
  - "@redocly/*"
  - tsdown
  - rolldown-plugin-dts
  - rolldown
  - "@rolldown/*"
  - oas
  - dedent
  - unrun
  - zod
  - valibot
  - "@valibot/*"
  - "@standard-schema/*"
  - import-without-cache
  - ws
  - "@vitest/*"
  - "shadcn"
  - "@oxc-project/*"
  - "@typescript/*"
  - picomatch
  - '@logtape/logtape'
  - '@napi-rs/*'
  - 'npm-check-updates'

npmPublishProvenance: true

npmRegistryServer: "https://registry.npmjs.org"

supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current

yarnPath: .yarn/releases/yarn-4.13.0.cjs
