import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
// import antiSlop from "ultracite/oxlint/anti-slop";
// import react from "ultracite/oxlint/react";
//import { selectJsPlugins, jsPluginsSettings } from "ultracite/oxlint/js-plugins";
import { selectJsPlugins } from "ultracite/oxlint/js-plugins";
import tanstack from "ultracite/oxlint/tanstack";
import tanstackJsPlugins from "ultracite/oxlint/tanstack/js-plugins";
import vitest from "ultracite/oxlint/vitest";

export default defineConfig({
  extends: [
    core,
    vitest,
    tanstack,
    tanstackJsPlugins,
    //antiSlop,
    //react,
    selectJsPlugins([
      //'react-doctor'
    ]),
  ],
  ignorePatterns: core.ignorePatterns,
  //settings: jsPluginSettings,
  overrides: [
    {
      files: ["*.ts", "*.tsx", ".mjs", ".js"],
      rules: {
        "unicorn/no-document-cookie": "off",
        "no-nested-ternary": "off",
        "no-param-reassign": "off",
        "react/function-component-definition": "off",
        "func-style": "off",
        "sort-keys": "off",
        "no-unreachable": "off",
        "no-use-before-define": "off",
        "typescript/no-extraneous-class": "off",
        "prefer-named-capture-group": "off",
        "no-promise-executor-return": "off",
        "promise/avoid-new": "off",
        eqeqeq: "off",
        "no-eq-null": "off",
        "jsdoc/require-param-description": "off",
        "no-unused-private-class-members": "off",
        "no-useless-constructor": "off",
        "jsdoc/require-throws-type": "off",
        "require-unicode-regexp": "off",
        "no-plusplus": "off",
        "prefer-spread": "off",
        "unicorn/prefer-spread": "off",
        "class-methods-use-this": "off",
        "prefer-destructuring": "off",
        "preserve-caught-error": "off",
        "prefer-template": "off",
        "no-useless-rename": "off",
        "no-unsafe-type-assertion": "off",
        "no-confusing-void-expression": "off",
        "prefer-readonly": "off",
        "strict-boolean-expressions": "off",
        "strict-void-return": "off",
        "no-unnecessary-type-parameters": "off",
        "prefer-nullish-coalescing": "off",
        "return-await": "off",
        "switch-exhaustiveness-check": "off",
        "no-unnecessary-boolean-literal-compare": "off",
        "no-unnecessary-template-expression": "off",
        "no-deprecated": "off",
        // 'anti-slop/require-safety-comment-for-type-assertion': 'off',
        // 'anti-slop/no-unsafe-dictionary-type': 'off',
        "require-yields": "off",
        "no-non-null-assertion": "off",
        "no-array-for-each": "off",
        "no-inline-comments": "off",
        curly: "off",
        "no-unused-vars": "off",
        "operator-assignment": "off",
        "object-shorthand": "off",
        "arrow-body-style": "off",
        "require-await": "off",
        "import/newline-after-import": "off",
        "import/consistent-type-specifier-style": "off",
        //'import/newline-after-import': 'off'
        // 'sonarjs/no-wildcard-import': 'off',
        "consistent-type-definitions": "off",
        "no-shadow": "off",
        "no-warning-comments": "off",
        "unicorn/catch-error-name": "off",
        complexity: "off",
        "no-explicit-any": "off",
        "unicorn/switch-case-braces": "off",
        "unicorn/prefer-number-coercion": "off",
        "no-await-in-loop": "off",
        "unicorn/filename-case": "off",
        "unicorn/consistent-function-scoping": "off",
        //'arrow-body-style': 'off',
        "unicorn/prefer-import-meta-properties": "off",
        //'no-useless-return': 'off',
        "jsdoc/check-tag-names": "off",
        "unicorn/numeric-separators-style": "off",
        "import/no-mutable-exports": "off",
        "prefer-await-to-then": "off",
        "prefer-await-to-callbacks": "off",
        // "no-shadow": "off",
        // "unicorn/filename-case": "off",
      },
    },
  ],
});
