import { DuckDBConnection } from "@duckdb/node-api";
import type { AsyncQResult, QMetaMaterializationSpan } from "@flowblade/core";
import { createQResultError, QMeta } from "@flowblade/core";
import { DuckdbDatasource } from "@flowblade/source-duckdb";

import type { Table } from "../../objects/table.ts";
import { SqlDuck, type ToTableResult } from "../../sql-duck.ts";
import { createRandomTable } from "../../table/create-random-table.ts";
import { isDuckdbValidIdentifier } from "../../validation/core/is-duckdb-valid-identifier.ts";
import type { KyselyQueryWithZodSchema } from "./kysely-query-with-zod-schema.ts";

const chunkSize = 1024;

type Params<TData extends unknown[]> = {
  duckConn: DuckdbDatasource | DuckDBConnection;
  table: KyselyQueryWithZodSchema;
  /**
   * Database where the temporary table is created (e.g. an attached file database).
   * Defaults to the connection's current database.
   */
  database?: string;
  /**
   * Schema where the temporary table is created (must already exist).
   * Defaults to the connection's current schema.
   */
  schema?: string;
  /**
   * Query to run in duckdb on the materialized table.
   * Its rows type is the one returned by `withMaterializedKyselyQuery`.
   */
  query: (options: {
    dsDuck: DuckdbDatasource;
    table: Table;
  }) => AsyncQResult<TData>;
};

export const createMaterializationSpan = (
  params: Omit<QMetaMaterializationSpan, "type">
): QMetaMaterializationSpan => {
  return {
    type: "materialization",
    ...params,
  };
};

const toDuckdbDatasource = (
  duckConn: DuckdbDatasource | DuckDBConnection
): DuckdbDatasource =>
  duckConn instanceof DuckDBConnection
    ? new DuckdbDatasource({ connection: duckConn })
    : duckConn;

/**
 * Best effort drop: a failure must not hide the query result (or its error).
 */
const dropTableQuietly = async (
  dsDuck: DuckdbDatasource,
  table: Table
): Promise<void> => {
  try {
    // the name is generated by createRandomTable (validated identifier)
    await dsDuck
      .getConnection()
      .run(`DROP TABLE IF EXISTS ${table.getFullName()}`);
  } catch {
    // ignore
  }
};

/**
 * Materialize a kysely query into a temporary duckdb table, run `query` on it,
 * then drop the table (whatever the outcome).
 */
export const withMaterializedKyselyQuery = async <
  TData extends unknown[] = unknown[],
>(
  params: Params<TData>
): AsyncQResult<TData> => {
  const { duckConn, table, query, database, schema } = params;
  // names are interpolated as-is in the DDL and in the final DROP statement
  for (const [kind, name] of [
    ["database", database],
    ["schema", schema],
  ] as const) {
    if (name !== undefined && !isDuckdbValidIdentifier(name)) {
      return createQResultError(
        { message: `Invalid ${kind} name '${name}'` },
        new QMeta({})
      );
    }
  }
  const dsDuck = toDuckdbDatasource(duckConn);
  const materializedTable = createRandomTable({
    prefix: "_materialized",
    database,
    schema,
  });

  try {
    let materialized: ToTableResult;
    try {
      materialized = await new SqlDuck({
        conn: dsDuck.getConnection(),
      }).toTable({
        chunkSize,
        rowStream: table.getQuery().stream({ chunkSize }),
        schema: table.getSchema(),
        table: materializedTable,
        autoCheckpoint: materializedTable.databaseName !== undefined,
      });
    } catch (error) {
      const reason = error instanceof Error ? error.message : String(error);
      return createQResultError(
        {
          message: `Can't materialize table ${materializedTable.getFullName()} - ${reason}`,
        },
        new QMeta({})
      );
    }

    const queryResult = await query({ dsDuck, table: materializedTable });
    if (!queryResult.error) {
      queryResult.meta.prependSpan(
        createMaterializationSpan({
          ddl: materialized.createTableDDL,
          timeMs: materialized.timeMs,
          affectedRows: materialized.totalRows,
          tableName: materializedTable.getFullName(),
        })
      );
    }
    return queryResult;
  } finally {
    // the table may also have been partially created when materialization failed
    await dropTableQuietly(dsDuck, materializedTable);
  }
};
