import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import vitest from "ultracite/oxlint/vitest";
//import tanstack from "ultracite/oxlint/tanstack";
//import tanstackJsPlugins from "ultracite/oxlint/tanstack/js-plugins";
//import antiSlop from "ultracite/oxlint/anti-slop";
// import { selectJsPlugins } from "ultracite/oxlint/js-plugins";

export default defineConfig({
  extends: [
    core,
    // vitest,
    //tanstack,
    //tanstackJsPlugins,
    //antiSlop,
    //selectJsPlugins([]),
  ],
  options: {
    typeAware: true,
    typeCheck: false,
  },
  ignorePatterns: core.ignorePatterns,
  // settings: jsPluginSettings,
  overrides: [
    {
      files: ["*.ts", "*.js", "*.mjs", "*.cjs"],
      rules: {
        "oxc/no-barrel-file": "off",
        eqeqeq: "off",
        "jsdoc/require-param-description": "off",
        "no-unused-private-class-members": "off",
        "no-useless-constructor": "off",
        "jsdoc/require-throws-type": "off",
        "require-unicode-regexp": "off",
        "no-plusplus": "off",
        "prefer-spread": "off",
        "unicorn/prefer-spread": "off",
        "class-methods-use-this": "off",
        "prefer-destructuring": "off",
        "preserve-caught-error": "off",
        "prefer-template": "off",
        "no-useless-rename": "off",
        "no-unsafe-type-assertion": "off",
        "no-confusing-void-expression": "off",
        "prefer-readonly": "off",
        "strict-boolean-expressions": "off",
        "strict-void-return": "off",
        "no-unnecessary-type-parameters": "off",
        "prefer-nullish-coalescing": "off",
        "return-await": "off",
        "switch-exhaustiveness-check": "off",
        "no-unnecessary-boolean-literal-compare": "off",
        "no-unnecessary-template-expression": "off",
        "no-deprecated": "off",
        // 'anti-slop/require-safety-comment-for-type-assertion': 'off',
        // 'anti-slop/no-unsafe-dictionary-type': 'off',
        "require-yields": "off",
        "no-non-null-assertion": "off",
        "no-array-for-each": "off",
        "func-style": "off",
        "no-inline-comments": "off",
        curly: "off",
        "sort-keys": "off",
        "no-unused-vars": "off",
        "operator-assignment": "off",
        "object-shorthand": "off",
        "arrow-body-style": "off",
        "require-await": "off",
        "import/newline-after-import": "off",
        "import/consistent-type-specifier-style": "off",
        //'import/newline-after-import': 'off'
        // 'sonarjs/no-wildcard-import': 'off',
        "consistent-type-definitions": "off",
        "no-shadow": "off",
        "no-warning-comments": "off",
        "unicorn/catch-error-name": "off",
        complexity: "off",
        "no-explicit-any": "off",
        "unicorn/switch-case-braces": "off",
        "unicorn/prefer-number-coercion": "off",
        "no-await-in-loop": "off",
        "unicorn/filename-case": "off",
        "unicorn/consistent-function-scoping": "off",
        //'arrow-body-style': 'off',
        "unicorn/prefer-import-meta-properties": "off",
        //'no-useless-return': 'off',
        "jsdoc/check-tag-names": "off",
        "unicorn/numeric-separators-style": "off",
      },
    },
    {
      files: ["*.test.ts", "*.spec.ts"],
      rules: {
        "func-name-matching": "off",
        "unicorn/consistent-function-scoping": "off",
        "require-unicode-regexp": "off",
        "no-deprecated": "off", // todo enable
        "no-unsafe-type-assertion": "off",
        "no-unsafe-member-access": "off",
        "strict-boolean-expressions": "off",
        "no-unsafe-assignment": "off",
        "prefer-named-capture-group": "off",
        "unicorn/no-useless-undefined": "off",
        "unicorn/prefer-bigint-literals": "off",
        "func-names": "off",
        "typescript/prefer-ts-expect-error": "off",
      },
    },
  ],
});
