name: flowblade-azurite

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.34.0
    restart: unless-stopped
    networks:
      - flowblade-net
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - azurite-data:/data:rw

volumes:
  azurite-data:

networks:
  flowblade-net:
    driver: bridge
    enable_ipv6: false
