name: flowblade-example-nextjs
services:
  app-debian:
    build:
      # Start from root of the monorepo
      context: ../../../../
      dockerfile: ./examples/apps/nextjs-app/docker/Dockerfile
    restart: no
    networks:
      - flowblade-net
    ports:
      - 3000:3000
    environment:
      - DOCKER_BUILDKIT=1

networks:
  flowblade-net:
    driver: bridge
    enable_ipv6: false
