ARG NODE_VERSION=24.14
ARG DISTROLESS_IMAGE=gcr.io/distroless/nodejs24-debian13
ARG DEBIAN_VERSION=trixie-slim
ARG COREPACK_VERSION=0.34.6


#############################################################
# Stage 1 - App extraction / pruning                        #
#############################################################

FROM node:${NODE_VERSION}-${DEBIAN_VERSION} AS prepare

RUN apt-get update \
  #&& apt-get install build-essential cmake curl unzip ca-certificates git jq --no-install-recommends -y \
  && apt-get install git jq --no-install-recommends -y \
  && rm -rf /var/cache/apt/* \
  ## Corepack won't be bundled in node 25+
  && npm i -g corepack@${COREPACK_VERSION} && corepack enable


WORKDIR /app

COPY --link package.json turbo.jsonc ./

# Install Turbo at the version declared by the pruned workspace.
# both local and docker are aligned on the package.json version.
RUN TURBO_VERSION=$(cat package.json | jq '.devDependencies["turbo"]' -r) npm i -g turbo@${TURBO_VERSION}

COPY --link . .

# https://turbo.build/repo/docs/handbook/deploying-with-docker
RUN turbo prune --scope=@examples/nextjs-app --docker --out-dir=./.turbo-pruned/nextjs-app/

#############################################################
# Stage 2 - App installation                                #
#############################################################

FROM prepare AS builder

ENV TZ=Etc/UTC

# Disabling some well-known postinstall scripts
ENV PRISMA_SKIP_POSTINSTALL_GENERATE=true
ENV HUSKY=0

WORKDIR /app

# First install the dependencies (as they change less often)
COPY --link .gitignore ./
COPY --from=prepare --link /app/.turbo-pruned/nextjs-app/json/ .
COPY --from=prepare --link /app/.turbo-pruned/nextjs-app/pnpm-lock.yaml ./pnpm-lock.yaml

# Option 1: run install without cache
#RUN pnpm install --frozen-lockfile

# Option 2: run install with buildx cache mount (buildx)
RUN --mount=type=cache,target=/root/.local/share/pnpm/store,id=pnpm-store,sharing=locked \
    pnpm install --frozen-lockfile

# Build the project
COPY --link --from=prepare /app/.turbo-pruned/nextjs-app/full/ .
COPY --link .gitignore turbo.jsonc tsconfig.base.json ./

ENV NEXT_BUILD_IGNORE_ESLINT=true
ENV NEXT_BUILD_IGNORE_TYPECHECK=true
ENV NEXT_BUILD_OUTPUT=standalone
ENV NODE_ENV=production
# ENV NEXT_BUILD_ENV_SENTRY_ENABLED=false
# ENV NEXT_BUILD_ENV_SENTRY_TRACING=false

RUN pnpm --filter @examples/db-sqlserver prisma-generate

RUN pnpm turbo run build --filter=@examples/nextjs-app
# Alternative we can also
#RUN pnpm turbo run build --filter=@examples/nextjs-app...

#############################################################
# Stage 3 - App runner                                      #
#############################################################

FROM ${DISTROLESS_IMAGE} AS runner

ARG NEXTJS_APP_PORT

# Bort PORT / HOSTNAME envs are respected by nextjs start/dev.
ENV HOSTNAME=0.0.0.0
ENV PORT=${NEXTJS_APP_PORT:-3000}
ENV TZ=Etc/UTC
ENV NODE_ENV=production

#RUN apt-get update \
#  && apt-get install tzdata --no-install-recommends -y \
#  && rm -rf /var/cache/apt/*

WORKDIR /app

#RUN addgroup --system --gid 1001 nodejs
#RUN adduser --system --uid 1001 nextjs

# Set the correct permission for prerender cache
#RUN mkdir .next
#RUN chown nextjs:nodejs .next

# Default distroless user
USER 65532:65532

COPY --from=builder  /app/examples/apps/nextjs-app/next.config.mjs \
                    /app/examples/apps/nextjs-app/package.json --chown=65532:65532 \
                    ./

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=65532:65532 /app/examples/apps/nextjs-app/.next/standalone ./
COPY --from=builder --chown=65532:65532 /app/examples/apps/nextjs-app/.next/static ./examples/apps/nextjs-app/.next/static
COPY --from=builder --chown=65532:65532 /app/examples/apps/nextjs-app/public ./examples/apps/nextjs-app/public

EXPOSE ${PORT}

CMD ["node", "examples/apps/nextjs-app/server.js"]
