name: flowblade-azurite

services:
  rustfs:
    image: rustfs/rustfs:1.0.0-alpha.90
    #restart: unless-stopped
    networks:
      - flowblade-net
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
      - RUSTFS_CONSOLE_ENABLE=true
    volumes:
      - rustfs-data:/data:rw

volumes:
  rustfs-data:

networks:
  flowblade-net:
    driver: bridge
    enable_ipv6: false
