name: CI-docs-website

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/actions/**'
      - '.github/workflows/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy-docs-website:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    env:
      NEXTJS_IGNORE_ESLINT: true
      NEXTJS_IGNORE_TYPECHECK: true
      NEXT_DISABLE_SOURCEMAPS: true
      NEXT_TELEMETRY_DISABLED: true
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: ⚙️Install pnpm and Node.js
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          runtime: node@24
          cache: true

      - name: ⏩ TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@118f869397261f74bc39cb8565f2d02c0ed4209f # v4.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          server-token: ${{ secrets.CI_TURBO_SERVER_TOKEN }}

      - name: 🕵️ Typecheck
        run: pnpm turbo run typecheck --filter='@docs/website' --token="${{ secrets.CI_TURBO_SERVER_TOKEN }}"

      - name: 🔬 ESLint checks
        run: pnpm turbo run lint --filter='@docs/website' --token="${{ secrets.CI_TURBO_SERVER_TOKEN }}"

      - name: 🏗 Build docs
        run: pnpm --filter @docs/website run build-static
        env:
          NEXT_BUILD_BASE_PATH: "/flowblade"
          NEXT_TELEMETRY_DISABLED: true

      - name: 🚀 Upload doc website artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./docs/out

      - name: 🚀 Deploy
        if: ${{ github.repository == 'belgattitude/flowblade' && contains('refs/heads/main',github.ref)}}
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1

      #- name: 🚀 Deploy
      #  if: ${{ github.repository == 'belgattitude/flowblade' && contains('refs/heads/main',github.ref)}}
      #  run: |
      #    git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      #    pnpm website:deploy -u "github-actions-bot <support+actions@github.com>"
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
