name: CI-docs-website

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/actions/**"
      - ".github/workflows/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy-docs-website:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PNPM_CONFIG_VERIFY_DEPS_BEFORE_RUN: "false"
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: ⚙️Install pnpm and Node.js
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          runtime: node@24
          cache: false
          node-version-file: false

      - name: ⏩ TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@118f869397261f74bc39cb8565f2d02c0ed4209f # v4.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          server-token: ${{ secrets.CI_TURBO_SERVER_TOKEN }}

      - name: 🕵️ Typecheck
        run: pnpm turbo run typecheck --filter='@docs/website' --token="${{ secrets.CI_TURBO_SERVER_TOKEN }}"

      - name: 🔬 ESLint checks
        run: pnpm turbo run lint --filter='@docs/website' --token="${{ secrets.CI_TURBO_SERVER_TOKEN }}"

      - name: 🏗 Build docs
        run: pnpm --filter @docs/website run build

      - name: 🚀 Deploy to Cloudflare Pages
        if: github.repository == 'belgattitude/flowblade' && github.ref == 'refs/heads/main'
        run: pnpm dlx wrangler@4.147.0 pages deploy ./docs/dist --project-name=flowblade --branch=main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
