name: CI-monorepo-integrity

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

permissions:
  contents: read

jobs:
  install-integrity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: ['node@24']
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: ⚙️Install pnpm and Node.js
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          runtime: ${{ matrix.runtime }}
          cache: true
          node-version-file: false

      - name: 🛟 Check monorepo duplicates
        run: pnpm dedupe --check

      - name: 🛡️ Check for security vulnerabilities
        run: pnpm audit --audit-level high

