name: CI-monorepo-integrity

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

permissions:
  contents: read

jobs:
  install-integrity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v7

      - name: ⚙️ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          package-manager-cache: false

      - name: 📥 Monorepo install
        uses: ./.github/actions/pnpm-install

      #- name: 🛟 Check monorepo dependency graph
      #  run: pnpm check:install

      #- name: 🦺 Syncpack checks - packages - lint-semver-ranges
      #  run: pnpm syncpack:check
